PANTHEONtech/StoneWork

.github/workflows/ci.yml
.github/workflows/release.yml

This PR adds initial CI/CD pipelines for StoneWork using GitHub Workflows.
- **CI workflow** - runs check/build/test job for PRs and pushes to main branch
- **Release workflow** - builds and pushes images to GitHub Container Registry
---
The testing examples with mockcnf seem to be failing on command `ip link`  for `vrf1` MTU. I assume it is because of different kernel version. Will need to investigate more. Alternatively we could disable these two tests for GitHub CI for now.

Add workflows

---

docker/proto-rootgen/Dockerfile

Building errors are caused by using newer protoc-gen-doc (protoc plugin) that uses feature of newer golang that is not used in Stonework (the embed feature). 
The ideal fix is to upgrade golang, but that can cause other problems. Therefore, i just fixed given protoc plugin to last good version that works.
Also to prevent further similar problems, i also fixed the other protoc plugin used to fixed version.

Fix for proto-rootgen image building

---

.github/workflows/release.yml
.gitmodules
CNF-INDEX.md
Makefile
docker/vpp-mellanox.Dockerfile
docs/ARCHITECTURE.md
docs/CNF_HOW_TO.md
docs/UPDATE_PROCEDURE.md
examples/testing/040-router6/config/config-with-arps.yaml
examples/testing/040-router6/config/day0-config.yaml
examples/testing/100-mock-cnf-module/test-stonework.sh
examples/testing/110-mock-cnf-standalone/test-cnf.sh
examples/testing/README.md
go.mod
plugins/cnfreg/plugin.go
vpp/abx/README.md

* All tests are passing without workarounds.
* I merged indexes reserved by organizations and specific CNF indexes into a single [file](https://github.com/samuel-dudik/StoneWork/blob/CNF-985/CNF-INDEX.md).
* The gen-docs.sh script is already present, so I just fixed the paths in documentation.

CNF-985 Various minor corrections

---

docker/vpp-test.Dockerfile

Without apt update, some deb packages from ubuntu repositories fail to download.

fixed dependency download in vpp-test docker image build

---

Makefile

Git tags that contain the -* suffix (e.g. 21.06.1-rc2) will from now on push images to ghcr.io only in the full version format (e.g. 21.06.1-rc2).
This PR also adds the stonework-vpp image to ghcr.io.

Fix image pushing to ghcr.io

---

vpp/abx/vpp2202/abx/abx.c

This commit fixes issues when an interface is configured as NAT outside together with ABX and NAT messes up or drops the packet before being punted by ABX.

fix: Make abx-ip4 node run before NAT

---

plugins/abx/descriptor/abx.go
plugins/abx/vppcalls/abx_vppcalls.go
plugins/abx/vppcalls/vpp2202/abx_vppcalls.go
plugins/abx/vppcalls/vpp2202/dump_abx_vppcalls.go
vpp/abx/vpp2202/abx/abx.h
vpp/abx/vpp2202/abx/abx_api.c
vpp/abx/vpp2202/abx/abx_if_attach.c

- fix missing DstMac field value in dump details message
- remove useless check if interface is physical on detach (attach does not check this)
- increase ABX plugin version to 1.2
- incomplete equal comparator did not compare dstmac/output iface
- dump did not resolve output interface
- fix resync of abx attached interfaces

Fix issues in ABX VPP plugin

---

vpp/abx/vpp2202/abx/abx_policy.c

Signed-off-by: Vladimir Bernolak <vladimir.bernolak@pantheon.tech>

fix: Correctly remove ABX policy with MAC change

---

vpp/abx/vpp2202/test/test_abx.py

Signed-off-by: Vladimir Bernolak <vladimir.bernolak@pantheon.tech>

Add tests for ABX VPP plugin

---

cmd/swctl/cmd_deploy.go
cmd/swctl/cmd_status.go

Also correct color highlighting for `swctl status -h` command.

Fix swctl deploy services command

---

scripts/build.sh

`docker build` truncated stderr output so it was redirected to stdout so user could read why the test failed. This solution was not made with much foresight, as when automatic CI testing was added later, stderr was always empty so workflow passed even when it should not.
This PR should hopefully fix the issue.
Signed-off-by: Peter Motičák <peter.moticak@pantheon.tech>

ci: Fix always passing VPP plugin test

---

README.md
docs/ARCHITECTURE.md
docs/CNF_HOW_TO.md
docs/UPDATE_PROCEDURE.md
docs/USERGUIDE.md
examples/getting-started/README.md
examples/nat-router/README.md
examples/telemetry-monitoring/test-stonework.sh
examples/testing/010-xconnect/Makefile
examples/testing/010-xconnect/test-stonework.sh
examples/testing/020-switch/Makefile
examples/testing/020-switch/test-stonework.sh
examples/testing/030-router/Makefile
examples/testing/030-router/test-stonework.sh
examples/testing/040-router6/Makefile
examples/testing/040-router6/README.md
examples/testing/040-router6/test-stonework.sh
examples/testing/110-mock-cnf-standalone/Makefile
examples/testing/110-mock-cnf-standalone/README.md
examples/testing/110-mock-cnf-standalone/test-cnf.sh
examples/testing/README.md
examples/testing/utils.sh
experiments/sr-mpls/Makefile

This PR replaces all occurences of standalone `docker-compose` (Compose V1) with compose plugin `docker compose` (Compose V2). As from July 2023 Docker Compose V1 stopped receiving updates ([more info here](https://docs.docker.com/compose/migrate/)). Moreover `swctl` already used V2 so this change unifies the usage of Compose across the codebase.
Mentions of Docker/Docker Compose in docs are also updated.

Migrate to Docker Compose V2

---

client/client.go
cmd/swctl/cli.go
cmd/swctl/cmd_config.go
cmd/swctl/cmd_deploy.go
cmd/swctl/cmd_status.go
cmd/swctl/cmd_support.go
cmd/swctl/cmd_trace.go
cmd/swctl/exec.go

Purpose of central executor is to mainly automatically set certain flags (if not set explicitly) of external commands to match those of `swctl`.

Add central command executor

---

client/client.go
cmd/swctl/cli.go
cmd/swctl/cmd.go
cmd/swctl/exec.go
cmd/swctl/options.go

Also pass `--composefile` swctl flag to Docker when executing `docker compose`.
Note: perhaps `GlobalOptions` struct and related method/field in `CLI` struct could be renamed to something like `GlobalFlags` to better distinguish it from functional `CliOptions`?

Merge global swctl flags into one structure

---

client/client.go
cmd/swctl/app/cmd_status.go

Currently there is no good way to determine that a container running in StoneWork Docker Compose project is a standalone CNF. Therefore we use a heuristic: if it is not StoneWork or a StoneWork module but it still contains running instance of vpp-agent then it is a standalone CNF. For now we check only the default vpp-agent HTTP port to see if vpp-agent is running which determines if we classify it as a standalone CNF or an auxiliary container. 
Also improve table output of `swctl status` command to show IP address and default ports of the standalone CNF.

Improve standalone CNF component detection

---

.github/workflows/release.yml

This PR fixes warnings from the release action(https://github.com/PANTHEONtech/StoneWork/actions/runs/6313188882):
```
release
The following actions uses node12 which is deprecated and will be forced to run on node16: docker/login-action@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
release
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
release
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
```

upgraded docker login action to prevent problems with soon-to-be deprecated github workflow commands

---

cmd/swctl/app/cmd_support.go

Fixed calling of `swctl support` that was failing due to multiple reasons:
1. bad `agentctl` parameters ordering
2. not handled nil pointer usage in code -> applied quick fix and reduced report scope (see FIXME in code)
Also simplified error handling logic and reorganized reporting to maximize reporting capabilities in case of errors.

fixed and simplified swctl support command

---

cmd/swctl/app/cmd_manage.go

Currently configuration generated by the manage command is printed into console making it cumbersome to copy paste it into desired file (especially in --interactive mode as user cannot just redirect it > into a file).
default name of file is generated by entity name and selected format. It can be overriden by --file flag where suffix must be the same as selected format

swctl: redirect output from command 'manage <Entity> create' to file

---

cmd/swctl/app/cmd_config.go

- changing flags to args
- deciding which flags belong to agentctl and which to swctl, deciding in run function
- merging both flagset to one help

swctl: config helper wrap 'agentctl --help' and merge with swctl

---

.github/workflows/ci.yml
.github/workflows/release.yml
README.md
cmd/swctl/app/docker/agentctl.Dockerfile
docker/dev.Dockerfile
docker/mockcnf/Dockerfile
docker/prod.Dockerfile
docker/proto-rootgen/Dockerfile
docker/tester.Dockerfile
docker/vpp-mellanox.Dockerfile
docs/GNS3_APPLIANCES.md
docs/USERGUIDE.md
scripts/vm/create-vm-image.sh

the vpp-base updated to ubuntu 22.04 and cause problems with docker image building

upgrade ubuntu to 22.04

---

cmd/swctl/app/cmd_manage.go
cmd/swctl/app/entity.go

Added possibility to use go template range construct to entities templates. For example:
```
vppConfig:
vrfs:
{{range $noninput_user_id := loop 1 ${USER_COUNT} }}
- id: {{ $noninput_user_id }}
{{- end}} 
```
where `USER_COUNT` is entity input variable and `noninput_user_id` is temporal loop variable (go template variable)
Note: the `noninput_` prefix is vital to identify variables not defined as entity input, because they need to be at some places in code handled in different way

swctl: added support for using go template range loops in entity configs

---

cmd/swctl/app/cmd_manage.go
cmd/swctl/app/entity.go

Adds possibility to control creation of extra files from entity based on condition. For example this code will deploy given yaml only for demo deployment (DEMO_DEPLOYMENT is entity input variable)
```
files:
- name: "additional-config-for-demo.yaml"
when: "${DEMO_DEPLOYMENT}"
content: |
...
```
The condition is fully-evaluated template (just as entity config) and its content is evaluated (strconv.ParseBool) to find whether to create this file ("when" content is parsed to true boolean) or not ("when" content is parsed to false boolean).

swctl: added usage condition for entity's extra file
